# Generated by Django 5.2.16 on 2026-09-17 13:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('club', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='parentprofile',
            name='number_of_children',
        ),
        migrations.AddField(
            model_name='parentprofile',
            name='bio',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='parentprofile',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
        migrations.AddField(
            model_name='parentprofile',
            name='nearest_bus_stop',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='parentprofile',
            name='address',
            field=models.TextField(blank=True, default=''),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='parentprofile',
            name='full_name',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='parentprofile',
            name='occupation',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='parentprofile',
            name='phone_number',
            field=models.CharField(blank=True, max_length=20),
        ),
    ]
