# Generated by Django 5.2.16 on 2026-08-25 17:43

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('club', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='share',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, db_index=True),
        ),
        migrations.AlterField(
            model_name='share',
            name='platform',
            field=models.CharField(blank=True, choices=[('facebook', 'Facebook'), ('x', 'X'), ('linkedin', 'LinkedIn'), ('whatsapp', 'WhatsApp'), ('copy', 'Copy Link')], max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='share',
            name='share_type',
            field=models.CharField(choices=[('internal', 'Internal'), ('external', 'External')], default='external', max_length=10),
        ),
        migrations.CreateModel(
            name='SocialAccount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('platform', models.CharField(choices=[('facebook', 'Facebook'), ('x', 'X'), ('linkedin', 'LinkedIn')], max_length=20)),
                ('platform_user_id', models.CharField(blank=True, max_length=255, null=True)),
                ('access_token', models.TextField(blank=True, null=True)),
                ('refresh_token', models.TextField(blank=True, null=True)),
                ('expires_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='social_accounts', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
