# Generated by Django 5.2.16 on 2026-09-20 15:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('club', '0002_remove_parentprofile_number_of_children_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='user_type',
            field=models.CharField(blank=True, choices=[('student', 'Student'), ('school', 'School'), ('teacher', 'Teacher'), ('parent', 'Parent'), ('admin', 'Admin')], max_length=20, null=True),
        ),
    ]
