# Generated by Django 5.2.16 on 2026-09-20 17:51

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('club', '0003_alter_user_user_type'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='parentprofile',
            name='bio',
        ),
        migrations.RemoveField(
            model_name='parentprofile',
            name='country',
        ),
        migrations.RemoveField(
            model_name='parentprofile',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='parentprofile',
            name='email',
        ),
        migrations.RemoveField(
            model_name='parentprofile',
            name='full_name',
        ),
        migrations.RemoveField(
            model_name='parentprofile',
            name='lga',
        ),
        migrations.RemoveField(
            model_name='parentprofile',
            name='nearest_bus_stop',
        ),
        migrations.RemoveField(
            model_name='parentprofile',
            name='occupation',
        ),
        migrations.RemoveField(
            model_name='parentprofile',
            name='slug',
        ),
        migrations.RemoveField(
            model_name='parentprofile',
            name='state',
        ),
        migrations.RemoveField(
            model_name='parentprofile',
            name='whatsapp_number',
        ),
        migrations.AlterField(
            model_name='parentprofile',
            name='avatar',
            field=models.ImageField(blank=True, null=True, upload_to='parent_avatars/'),
        ),
        migrations.AlterField(
            model_name='parentprofile',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
